id             ::= /[a-zA-Z-][a-zA-Z0-9-]*/
key            ::= /[a-zA-Z][a-zA-Z0-9]*/
stringLiteral  ::= "\"" /[^"]*/ "\""

AtomicType     ::= "leaf"
                 | "node" id
DepType        ::= AtomicType ("[]")*
DepDef         ::= key ":" DepType NEWLINE

RefSourceExpr  ::= "$deps." key
                 | "$members." key "." key
RefExpr        ::= RefSourceExpr ("." key)*
ValueExpr      ::= RefExpr
                 | "leaf" stringLiteral
                 | "node" id ArgBlock
                 | "[" (ValueExpr ("," ValueExpr)*)? "]"
ArgDef         ::= key ":" ValueExpr NEWLINE
ArgBlock       ::= (NEWLINE (INDENT ArgDef* DEDENT))?

MemberExpr     ::= "rule" id ArgBlock
                 | "derive" id ArgBlock
                 | "nl" stringLiteral
                 | "seq" MemberExpr
MemberDef      ::= key "=" MemberExpr NEWLINE

BodyDef        ::= key ":" ValueExpr NEWLINE

RuleDef        ::= "rule" id ":" NEWLINE
                   INDENT "desc"  stringLiteral NEWLINE
                   "depends" ":" NEWLINE
                   INDENT (DepDef)* DEDENT
                   "members" ":" NEWLINE
                   INDENT (MemberDef)* DEDENT
                   "body" ":" NEWLINE
                   INDENT (BodyDef)* DEDENT
                   DEDENT
RuleSet        ::= (RuleDef)*