ir             ::= /[a-zA-Z-][a-zA-Z0-9-]*/
key            ::= /[a-zA-Z][a-zA-Z0-9]*/
stringLiteral  ::= "\"" /[^"]*/ "\""

AtomicType     ::= "leaf"
                 | "node" ir
ParamType      ::= AtomicType ("[]")*
ParamDef       ::= key ":" ParamType NEWLINE

RefSourceExpr  ::= "$args." key
                 | "$subtasks." key "." key
RefExpr        ::= RefSourceExpr ("." key)*
ValueExpr      ::= RefExpr
                 | "leaf" stringLiteral
                 | "node" ir ArgBlock
                 | "[" (ValueExpr ("," ValueExpr)*)? "]"
ArgDef         ::= key ":" ValueExpr NEWLINE
ArgBlock       ::= (NEWLINE (INDENT ArgDef* DEDENT))?

SubtaskExpr    ::= "op" ir ArgBlock
                 | "conv" ir ArgBlock
                 | "nl" stringLiteral
                 | "map" SubtaskExpr
SubtaskDef     ::= key "=" SubtaskExpr NEWLINE

OutputDef      ::= key ":" ValueExpr NEWLINE

OperationDef   ::= "operation" ir ":" NEWLINE
                   INDENT "desc"  stringLiteral NEWLINE
                   "params" ":" NEWLINE
                   INDENT (ParamDef)* DEDENT
                   "steps" ":" NEWLINE
                   INDENT (SubtaskDef)* DEDENT
                   "outputs" ":" NEWLINE
                   INDENT (OutputDef)* DEDENT
                   DEDENT
OperationFile  ::= (OperationDef)*