<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Types\Composition\CompositionContext.fs" />
        <Compile Include="Types\Composition\SemanticOperation.fs" />
        <Compile Include="Grammar\ParseContext.fs" />
        <Compile Include="Grammar\Parsers\Lexer.fs" />
        <Compile Include="Grammar\Parsers\Types.fs" />
        <Compile Include="Grammar\Parsers\Vars.fs" />
        <Compile Include="Grammar\Parsers\StringTemplate.fs" />
        <Compile Include="Grammar\Parsers\PrimitiveExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\DynamicExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\SeqExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\ValueExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\RuleExpr.fs" />
        <Compile Include="Utils\TaskUtils.fs" />
        <EmbeddedResource Include="Migrations\*.sql" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FParsec" Version="1.1.1" />
      <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
      <PackageReference Update="FSharp.Core" Version="10.1.203" />
      <PackageReference Include="Npgsql" Version="10.0.2" />
    </ItemGroup>

</Project>
