<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Grammar\ParseContext.fs" />
        <Compile Include="Grammar\Parsers\Lexer.fs" />
        <Compile Include="Grammar\Parsers\Types.fs" />
        <Compile Include="Grammar\Parsers\Vars.fs" />
        <Compile Include="Grammar\Parsers\StringTemplate.fs" />
        <Compile Include="Grammar\Parsers\PrimitiveExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\DynamicExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\SeqExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\ValueExpr.fs" />
        <Compile Include="Grammar\Parsers\Domain\HeaderExpr.fs" />
        <Compile Include="Utils\TaskUtils.fs" />
        <Compile Include="ConceptExpr.fs" />
        <Compile Include="ActionExpr.fs" />
        <Compile Include="RuleExpr.fs" />
        <Compile Include="DocumentParser.fs" />
        <Compile Include="Repositories\Abstractions\IDocumentRepository.fs" />
        <Compile Include="Repositories\Abstractions\IRecordRepository.fs" />
        <Compile Include="Repositories\Abstractions\IActionRepository.fs" />
        <Compile Include="Repositories\Abstractions\IRuleRepository.fs" />
        <Compile Include="Repositories\Abstractions\ICommunityRepository.fs" />
        <Compile Include="Repositories\Implementations\RecordRepository.fs" />
        <Compile Include="Repositories\Implementations\ActionRepository.fs" />
        <Compile Include="Repositories\Implementations\RuleRepository.fs" />
        <Compile Include="Repositories\Implementations\CommunityRepository.fs" />
        <Compile Include="Extensions\DependencyInjectionExtensions.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FParsec" Version="1.1.1" />
      <PackageReference Include="FSharp.SystemTextJson" Version="1.4.36" />
      <PackageReference Update="FSharp.Core" Version="10.1.300" />
      <PackageReference Include="Npgsql" Version="10.0.3" />
      <PackageReference Include="Pgvector" Version="0.3.2" />
    </ItemGroup>

</Project>
